use dblojinha;
CREATE TABLE PRODUTOS(
[CODIGO] [INT] IDENTITY (1,1) NOT NULL,
NOME VARCHAR(100) NOT NULL,
PRECO DECIMAL(10, 2) NOT NULL,
ESTOQUE INT,
CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED
(
    [CODIGO]
    ) ON [PRIMARY] 
) ON [PRIMARY]
GO 

insert into PRODUTOS(NOME, PRECO, ESTOQUE)
VALUES('Computador Gamer', 15000.00, 15);

insert into PRODUTOS(NOME, PRECO, ESTOQUE)
VALUES('Impressora 3D', 5000.00, 10);  

select * from PRODUTOS