use dblojinha;
CREATE TABLE CLIENTES(
[CODIGO] [INT] IDENTITY (1,1) NOT NULL,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED
(
    [CODIGO]
    ) ON [PRIMARY] 
) ON [PRIMARY]
GO 
INSERT INTO CLIENTES(NOME, EMAIL, TELEFONE)
VALUES('Karoline Fernandes Jandre', 'karoline@gmail', '69983844763')

select * from CLIENTES;